# Generated by Django 4.2.6 on 2024-07-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayOrder',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('attempts', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('payment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('error_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment_app.razorpayorder')),
            ],
        ),
    ]
