# Generated by Django 5.1.1 on 2024-09-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='razorpaypayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
