# Generated by Django 4.2 on 2023-08-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0010_subcategorymodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductImage', models.ImageField(blank=True, upload_to='product')),
                ('brandName', models.CharField(max_length=100)),
                ('ProductPrice', models.IntegerField()),
                ('sellerName', models.CharField(max_length=100)),
                ('ProductDetail', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.categorymodel')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.subcategorymodel')),
            ],
        ),
    ]
