# Generated by Django 4.2 on 2023-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='ProductImage',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
    ]
