# Generated by Django 4.2.6 on 2024-07-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_productmodel_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
