# Generated by Django 4.2.6 on 2024-08-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
