# Generated by Django 4.2.6 on 2024-08-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_productsize_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='price',
            new_name='additional_price',
        ),
    ]
