# Generated by Django 5.1.1 on 2024-11-07 11:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_rename_price_productsize_additional_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='ProductImage',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product/'),
        ),
    ]
