# Generated by Django 5.1.1 on 2024-11-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0013_alter_subcategorymodel_subcategoryimage'),
        ('product_app', '0007_alter_productmodel_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category_app.categorymodel'),
        ),
    ]
