# Generated by Django 4.2 on 2023-08-14 12:58

from django.db import migrations, models
import django.db.models.deletion
# import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base_app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
