# Generated by Django 4.2 on 2023-08-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
