# Generated by Django 4.2 on 2023-08-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
