# Generated by Django 4.2.5 on 2023-10-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_address',
            field=models.TextField(default=None, null=True),
        ),
    ]
