# Generated by Django 4.2.5 on 2023-10-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_ordermodel_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_address',
        ),
    ]
