# Generated by Django 4.2.6 on 2023-10-31 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_remove_ordermodel_order_item_ordermodel_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_item',
        ),
    ]
