# Generated by Django 4.2.6 on 2023-11-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_orderitem_ordermodel_ordered_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='razorpay_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
