# Generated by Django 4.2.6 on 2023-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_ordermodel_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='razorpay_payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='razorpay_signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
