# Generated by Django 4.2.6 on 2024-08-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0012_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
