# Generated by Django 4.2.6 on 2024-08-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_productsize'),
        ('order_app', '0013_alter_ordermodel_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.productsize'),
        ),
    ]
