# Generated by Django 4.2 on 2023-08-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_categorymodel_subcategorymodel_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='categoeyImage',
            field=models.ImageField(null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategoryImage',
            field=models.ImageField(null=True, upload_to='subcategory'),
        ),
    ]
