# Generated by Django 4.2 on 2023-08-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0003_alter_categorymodel_categoeyimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='categoeyImage',
            field=models.ImageField(blank=True, default='', upload_to='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategoryImage',
            field=models.ImageField(blank=True, default='', upload_to='subcategory'),
            preserve_default=False,
        ),
    ]
