# Generated by Django 4.2 on 2023-08-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0004_alter_categorymodel_categoeyimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='subcategorymodel',
            old_name='subcategory',
            new_name='subcategoryName',
        ),
    ]
