# Generated by Django 4.2 on 2023-08-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0005_rename_category_categorymodel_categoryname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='categoeyImage',
            new_name='categoryImage',
        ),
    ]
