# Generated by Django 4.2 on 2023-08-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0007_categorymodel_slug_subcategorymodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorymodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='SubCategoryModel',
        ),
    ]
