# Generated by Django 4.2 on 2023-08-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
