# Generated by Django 4.2 on 2023-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0010_subcategorymodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='categoryImage',
            field=models.ImageField(blank=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategoryImage',
            field=models.ImageField(blank=True, upload_to='subcategory/'),
        ),
    ]
