# Generated by Django 5.1.1 on 2024-11-07 11:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0011_alter_categorymodel_categoryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='categoryImage',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='category/'),
        ),
    ]
