# Generated by Django 5.1.1 on 2024-11-07 11:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0012_alter_categorymodel_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategoryImage',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='subcategory/'),
        ),
    ]
