# Generated by Django 4.2.6 on 2024-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_cartitemmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
