# Generated by Django 4.2.5 on 2023-10-07 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0003_userprofile_firstname_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('ARUNACHAL PRADESH', 'Arunachal Pradesh'), ('ANDMAN & NICOBAR', 'Andman & Nicobar'), ('ASSAM', 'Assam'), ('BIHAR', 'Bihar'), ('CHANDIGARH', 'Chandigarh'), ('CHATTISGADH', 'Chattisgadh'), ('DADRA NAGAR', 'Dadra Nagar'), ('DAMAN & DIU', 'Daman & Diu'), ('DELHI', 'Delhi'), ('GOA', 'Goa'), ('GUJRAT', 'Gujrat'), ('HARYANA', 'Haryana'), ('HIMACHAL PRADESH', 'Himachal Pradesh'), ('JAMMU', 'Jammu'), ('JARKHAND', 'Jarkhand'), ('KARNATAKA', 'Karnataka'), ('KERALA', 'Kerala'), ('LADAKH', 'Ladakh'), ('MADHYA PRADESH', 'Madhya Pradesh'), ('MANIPUR', 'Manipur'), ('MAHARASHTRA', 'Maharashtra'), ('MEGHALAYA', 'Meghalaya'), ('MIZORAM', 'Mizoram'), ('NAGALAND', 'Nagaland'), ('ODHISHA', 'Odhisha'), ('PUNJAB', 'Punjab'), ('RAJASTHAN', 'Rajasthan'), ('SIKKIM', 'Sikkim'), ('TRIPURA', 'Tripura'), ('TAMIL NADU', 'Tamil Nadu'), ('TELGANA', 'Telgana'), ('UTAR PRADES', 'Utar Prades'), ('UTRAKHAND', 'Utrakhand'), ('WEST BENAGAL', 'West Benagal')], max_length=255)),
                ('landmark', models.CharField(max_length=100)),
                ('optionalnumber', models.CharField(blank=True, max_length=10)),
                ('addresstype', models.CharField(choices=[('H', 'HOME'), ('W', 'WORK')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
