# Generated by Django 4.2.5 on 2023-10-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='addresstype',
            field=models.CharField(choices=[('Home', 'HOME'), ('Work', 'WORK')], max_length=10),
        ),
    ]
