# Generated by Django 4.2.5 on 2023-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_useraddress_addresstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andman & Nicobar', 'Andman & Nicobar'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chattisgadh', 'Chattisgadh'), ('Dadra Nagar', 'Dadra Nagar'), ('Daman & Diu', 'Daman & Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu', 'Jammu'), ('Jarkhand', 'Jarkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Manipur', 'Manipur'), ('Maharashtra', 'Maharashtra'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odhisha', 'Odhisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tripura', 'Tripura'), ('Tamil Nadu', 'Tamil Nadu'), ('Telgana', 'Telgana'), ('Utar Prades', 'Utar Prades'), ('Utrakhand', 'Utrakhand'), ('West Benagal', 'West Benagal')], max_length=255),
        ),
    ]
